### ISSUE TITLE
Refactor ExitProcessor and its tests

### ISSUE THREAD

**Issue by pdobacz** [omisego/elixir-omg#608]
As it was noted, `ExitProcessor` either is rotting fast or has already rotted.

This issue is to track the tidying process, comprising of (among others, first draft list):
 - [x] tidies and dries to the imperative shell `exit_processor.ex` #609 
 - [x] streamlining the processing of standard exit challenges, making logic more testable and tested #618 
 - [x] reducing the test brittleness by swapping out heavy use of fixtures for helper functions #631 
 - [x] drying of `exit_processor/core_test.exs` using the above #631 
 - [x] separate testing of compatibility with `OMG.State.Core` from the rest of tests #631 
 - [x] refactors and drying in the logic module `exit_processor/core.ex` #684
 - [x] (optionally, if still required) splitting code/tests across more files #837 
 - [x] tidy handling of input-output indices (0-3 vs 0-7) #684
 - [x] increase readability and dry the invalid piggyback detection and proof building #684
 - ~reduce interactions with `Eth`, to consider:~
    - ~drop checking `status` of exits~ - can't do that - if an old exit is invalid during a small period of time (while syncing) it would cause `unchallenged_exit` and halt
    - ~store `exit_id` (or `txbytes`) from `call_data` and store in `OMG.DB`~ - meh, better do it after ALD lands
 - [x] investigate and improve performance issues related (possibly different issue) #754

**Comment by pdobacz** [comment]
as the last of planned tidies finally got merged, closing this :tada:
