### ISSUE TITLE
Improved tests coverage

### ISSUE THREAD

**Issue by Pongch** [omisego/elixir-omg#853]
As a network operator, I would like to have stronger guarantees that the smart contract and elixir-omg codebase work as expected so I don't run into production issues.

**Comment by Pongch** [comment]
Breaking this down to 3 issues/tasks
@pdobacz 
1. elixir vs solidity compatibility test 
2. long running & property test for contract 
3. make a property test that creates various transactions and test exits,

**Comment by pdobacz** [comment]
1. [ ] elixir vs solidity compatibility test https://github.com/omisego/elixir-omg/issues/901
2. [ ] long running test for contract https://github.com/omisego/plasma-contracts/issues/217
3. [ ] property test for contract  https://github.com/omisego/plasma-contracts/issues/219
4. elixir-omg property test (I'm opting to skip this as a rather involved task with what seems to me like much smaller gain)
